"""your message

Revision ID: 520355746473
Revises: f75deeb14185
Create Date: 2024-07-05 14:49:58.803034

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '520355746473'
down_revision = 'f75deeb14185'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
